<a href="https://colab.research.google.com/github/mukhammaddiyor01/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Pandas bizga datalarni ustun holatiga keltirib ular bilan ishlashda yordamga kelar ekan

In [1]:
import pandas as pd

In [5]:
print(pd.__version__)

2.2.3

In [13]:
mydataset = {
    'cars': ['BMW M3 F80 CS', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'],
    'counts': [3, 7, 2, 5, 6, 7, 10],
    'ranks': ["The Best", "Ok", "Good", 'Ok', 'Ok', 'Ok', 'The Best']

}

print(mydataset)
print('=======')

df = pd.DataFrame(mydataset)
print(df)

{'cars': ['BMW M3 F80 CS', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'], 'counts': [3, 7, 2, 5, 6, 7, 10], 'ranks': ['The Best', 'Ok', 'Good', 'Ok', 'Ok', 'Ok', 'The Best']}
=======
            cars  counts     ranks
0  BMW M3 F80 CS       3  The Best
1          Volvo       7        Ok
2           Ford       2      Good
3          Tesla       5        Ok
4        Ferrari       6        Ok
5           Ford       7        Ok
6            BMW      10  The Best

In [14]:
df.head(8) # default 5 rows

            cars  counts     ranks
0  BMW M3 F80 CS       3  The Best
1          Volvo       7        Ok
2           Ford       2      Good
3          Tesla       5        Ok
4        Ferrari       6        Ok
5           Ford       7        Ok
6            BMW      10  The Best

In [15]:
df.tail(7) # ohiridan 5ta ko'rsatadi

            cars  counts     ranks
0  BMW M3 F80 CS       3  The Best
1          Volvo       7        Ok
2           Ford       2      Good
3          Tesla       5        Ok
4        Ferrari       6        Ok
5           Ford       7        Ok
6            BMW      10  The Best

In [16]:
df.shape # datamizni shapeini aniqlab beradi

(7, 3)

In [17]:
df.columns # faqat columns olib beradi va typeini ko'rsatadi

Index(['cars', 'counts', 'ranks'], dtype='object')

In [18]:
df.dtypes

cars      object
counts     int64
ranks     object
dtype: object

In [21]:
print(df)

            cars  counts     ranks
0  BMW M3 F80 CS       3  The Best
1          Volvo       7        Ok
2           Ford       2      Good
3          Tesla       5        Ok
4        Ferrari       6        Ok
5           Ford       7        Ok
6            BMW      10  The Best

In [20]:
df.describe() # qanday statistika bo'lyapti ko'rsatar ekan/  numerical columns only

          counts
count   7.000000
mean    5.714286
std     2.690371
min     2.000000
25%     4.000000
50%     6.000000
75%     7.000000
max    10.000000

In [22]:
df.describe(include="all") #barchasini ko'rsatadi

        cars     counts ranks
count      7   7.000000     7
unique     6        NaN     3
top     Ford        NaN    Ok
freq       2        NaN     4
mean     NaN   5.714286   NaN
std      NaN   2.690371   NaN
min      NaN   2.000000   NaN
25%      NaN   4.000000   NaN
50%      NaN   6.000000   NaN
75%      NaN   7.000000   NaN
max      NaN  10.000000   NaN

In [25]:
df.iloc[0] # tanlangan row ni olib berar ekan/ -1 qilinsa orqadan malumot olib berar ekan/ [1:4]-da 1dan 3-qatorgacha olib beradi

cars      BMW M3 F80 CS
counts                3
ranks          The Best
Name: 0, dtype: object

In [26]:
df.loc[:, "cars"] # birinchi qiyman 'row', ikkinchi qiymat 'column'

0    BMW M3 F80 CS
1            Volvo
2             Ford
3            Tesla
4          Ferrari
5             Ford
6              BMW
Name: cars, dtype: object

In [31]:
df[df["counts"] != 3]

      cars  counts     ranks
1    Volvo       7        Ok
2     Ford       2      Good
3    Tesla       5        Ok
4  Ferrari       6        Ok
5     Ford       7        Ok
6      BMW      10  The Best

In [32]:
df[df["cars"] == "Tesla"]

    cars  counts ranks
3  Tesla       5    Ok

In [34]:
# df.mean(numeric_only=True) # o'rtacha sonni olib berar ekan
df["counts"].mean()

np.float64(5.714285714285714)

In [35]:
df.sum()

cars      BMW M3 F80 CSVolvoFordTeslaFerrariFordBMW
counts                                           40
ranks                  The BestOkGoodOkOkOkThe Best
dtype: object

In [36]:
df.min()

cars       BMW
counts       2
ranks     Good
dtype: object

In [37]:
df.max()

cars         Volvo
counts          10
ranks     The Best
dtype: object

In [38]:
df.median(numeric_only=True) #middle valueni olib berar ekan

counts    6.0
dtype: float64

In [39]:
df.count() # healthy qiymatlarni olib berar ekan

cars      7
counts    7
ranks     7
dtype: int64

In [40]:
df.std(numeric_only=True) #standart deviation

counts    2.690371
dtype: float64

In [41]:
data_with_missing = {
    "cars": ["BMW M3 F80 CS", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 5, 6, None, 10],
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

            cars  counts
0  BMW M3 F80 CS     3.0
1          Volvo     7.0
2           None     NaN
3          Tesla     5.0
4        Ferrari     6.0
5           None     NaN
6           Ford    10.0

In [42]:
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True    True
6  False   False

In [43]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [44]:
df_missing.dropna() # unhealthy bo'lsa drop qilarkan

            cars  counts
0  BMW M3 F80 CS     3.0
1          Volvo     7.0
3          Tesla     5.0
4        Ferrari     6.0
6           Ford    10.0

In [45]:
df_missing.dropna(how="all")

            cars  counts
0  BMW M3 F80 CS     3.0
1          Volvo     7.0
3          Tesla     5.0
4        Ferrari     6.0
6           Ford    10.0

In [46]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [47]:
df_missing.dropna(subset=['counts'])

            cars  counts
0  BMW M3 F80 CS     3.0
1          Volvo     7.0
3          Tesla     5.0
4        Ferrari     6.0
6           Ford    10.0

In [48]:
df_missing.fillna(0)

            cars  counts
0  BMW M3 F80 CS     3.0
1          Volvo     7.0
2              0     0.0
3          Tesla     5.0
4        Ferrari     6.0
5              0     0.0
6           Ford    10.0

In [49]:
df_missing.fillna("unknown")

            cars   counts
0  BMW M3 F80 CS      3.0
1          Volvo      7.0
2        unknown  unknown
3          Tesla      5.0
4        Ferrari      6.0
5        unknown  unknown
6           Ford     10.0

In [50]:
df_missing.fillna({"cars": "unknown", "counts": 0})

            cars  counts
0  BMW M3 F80 CS     3.0
1          Volvo     7.0
2        unknown     0.0
3          Tesla     5.0
4        Ferrari     6.0
5        unknown     0.0
6           Ford    10.0

In [55]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(30)

# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S

In [57]:
df.to_excel("test.xlsx")

In [58]:
# Series => 1D arraylar bilan ishlashi
cars = pd.Series(["BMW M3 F80 CS", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"])
print(cars)

0    BMW M3 F80 CS
1            Volvo
2             Ford
3            Tesla
4          Ferrari
5             Ford
6              BMW
dtype: object

In [59]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW M3 F80 CS', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']